[package]
name = "lot"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.1.8", features = ["derive"] }
serde = { version = "1.0.154", features = ["derive"] }
directories = "4.0.1"
bincode = "1.3.3"
rand = "0.8.5"
